name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/sum-server" .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/sum-server"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest image
            echo "Pulling latest Docker image..."
            docker pull "${{ secrets.DOCKER_USERNAME }}/sum-server"

            # Stop and remove the old container (if it exists)
            echo "Stopping and removing old container if it exists..."
            docker stop sum-server || true
            docker rm sum-server || true

            # Run the new container
            echo "Running new container..."
            docker run -d -p 3001:3001 -p 3002:3002 --name sum-server "${{ secrets.DOCKER_USERNAME }}/sum-server"
